# Generated by Django 5.1.6 on 2025-02-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtalesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='reported',
            options={'verbose_name_plural': 'Reports'},
        ),
    ]
