# Generated by Django 5.1.7 on 2025-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtalesapp', '0002_remove_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
