# Generated by Django 5.1.6 on 2025-03-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airtalesapp", "0002_alter_journalentry_options_alter_reported_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reported",
            options={"verbose_name_plural": "Reported Entries"},
        ),
    ]
