# Generated by Django 5.1.7 on 2025-03-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtalesapp', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
