# Generated by Django 5.1.6 on 2025-03-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airtalesapp", "0003_alter_reported_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reported",
        ),
    ]
