# Generated by Django 5.1.7 on 2025-03-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtalesapp', '0004_journalentry_latitude_journalentry_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
