# Generated by Django 5.1.7 on 2025-03-09 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtalesapp', '0005_journalentry_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='likes',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
