# Generated by Django 5.1.7 on 2025-03-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtalesapp', '0006_remove_journalentry_likes_journalentry_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airtalesapp.prompt'),
        ),
    ]
