# Generated by Django 5.1.7 on 2025-03-16 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtalesapp', '0007_journalentry_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtalesapp.journalentry')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reported Entries',
                'unique_together': {('userID', 'entryID')},
            },
        ),
    ]
